In [30]:
import tensorflow as tf
tf.constant(1)  # 定义常量，普通的tensor
tf.constant(1.)  # 定义常量，普通的tensor
tf.constant([True, False])  # 定义常量，普通的tensor
tf.constant('hello nick')


with tf.device('cpu'):
    a = tf.constant([1])
with tf.device('gpu'):
    b = tf.constant([1])
  
a.device # 设备属性
a.gpu()  # cpu转gpu
a.numpy()  # 获取numpy数据类型
a.shape  # 获取a的属性
a.ndim  # 获取维度
tf.rank(a)  # 获取维度

#a.name  # 1.+历史遗留问题


print(a.device)
print(b.device)

print(a.shape )
print(tf.rank(a))


/job:localhost/replica:0/task:0/device:CPU:0
/job:localhost/replica:0/task:0/device:CPU:0
(1,)
tf.Tensor(1, shape=(), dtype=int32)


In [31]:
import tensorflow as tf
import numpy as np 
a = np.arange(5)
aa = tf.convert_to_tensor(a,dtype=tf.int32) # numpy转tensor
print(a)
print(aa)


b = tf.constant([0,1])
tf.cast(b,dtype=tf.bool) # int --》bool
print(b)
# tf.Variable
a = tf.range(5)
b = tf.Variable(a) # tensor转为Variable后具有求导的特性，即自动记录a的梯度相关信息
b.name # Variable:0

b = tf.Variable(a, name='input_data')
b.name # input_data:0
b.trainable # True

isinstance(b,tf.Tensor)  # False
isinstance(b,tf.Variable)  # True
tf.is_tensor(b)  # True  # 推荐使用



[0 1 2 3 4]
tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)
tf.Tensor([0 1], shape=(2,), dtype=int32)


True

In [33]:
import numpy as np
import tensorflow as tf

tf.convert_to_tensor(np.ones([2, 3]))


# tf.convert_to_tensor([1, 2])

tf.convert_to_tensor([[1], [2.]])

tf.random.normal([10, 10], mean=1, stddev=1)

# 截断的正态分布，
tf.random.truncated_normal([2, 2], mean=0, stddev=1)

<tf.Tensor: id=232, shape=(2, 2), dtype=float32, numpy=
array([[ 0.39041165, -0.19881016],
       [ 1.2726002 ,  1.2615964 ]], dtype=float32)>